### ISSUE TITLE
BitBucket build status API forces the need of HTTPS

### ISSUE THREAD

**Issue by hugowschneider** [opendevstack/ods-jenkins-shared-library#180] opened 2020-01-13 12:57 UTC
The call for setting the build status is set to use HTTPS and does not allow insecure connections nor HTTP connections.

https://github.com/opendevstack/ods-jenkins-shared-library/blob/1bd490154235c405bb0d32354ba14a8d25993d37/src/org/ods/OdsPipeline.groovy#L201-L209

With the current settings is impossible to check build status flag during tests and you be easier if we had flags/settings for both options: HTTP or insecure HTTPS being HTTP easier for tests.

**Comment by michaelsauter** [comment] 2020-01-13 12:59
Duplicate of #74.

**Closed by michaelsauter** 2020-01-13 12:59 UTC
Labels: enhancement
