### ISSUE TITLE
GitService.mergedIssueId/mergedIssueBranch doesn't match (Regression from #437)

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/ods-jenkins-shared-library#587] opened 2021-02-23 11:06 UTC
**Describe the bug**

In #437 I'm suggesting to use a different format code to sanitize the git commit message for `context.gitCommitMessage` and for 

The original commit for this i here: fb664f4

The change requires that all regex patterns that deal with the commit message need to be checked.

Failing regex, at least, here:

* https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/services/GitService.groovy#L33

**To Reproduce**
1. Create a branch
2. Create a commit
3. Create a Merge Request
4. When using `org.ods.services.GitService.mergedIssueId(context.projectId, context.repoName, context.gitCommitMessage)` it will never match because the regex is not matching any more

```groovy
  workingGitCommitMessage = "Merge pull request #62 in ODM/odm-components from bugfix/ODM-509-trigger-mergedissueid to feature/ODM-508-debug-ods-regression"
  final String mergedIssueId = org.ods.services.GitService.mergedIssueId(context.projectId, context.repoName, workingGitCommitMessage )
  final String mergedBranch = org.ods.services.GitService.mergedIssueId(context.projectId, context.repoName, workingGitCommitMessage )
  echo "mergedIssueId: >>${mergedIssueId}"
  echo "mergedBranch: >>${mergedBranch}"
```
```groovy
  // "Merge-pull-request-62-in-ODM-odm-components-from-bugfix-ODM-509-trigger-mergedissueid-to-feature-ODM-508-debug-ods-regression"
  failingGitCommitMessage = context.gitCommitMessage
  final String mergedIssueId = org.ods.services.GitService.mergedIssueId(context.projectId, context.repoName, failingGitCommitMessage )
  final String mergedBranch = org.ods.services.GitService.mergedIssueId(context.projectId, context.repoName, failingGitCommitMessage )
  echo "mergedIssueId: >>${mergedIssueId}"
  echo "mergedBranch: >>${mergedBranch}"
```

**Expected behavior**

`org.ods.services.GitService.mergedIssueId(context.projectId, context.repoName, context.gitCommitMessage)` should match again

**Screenshots**

![grafik](https://user-images.githubusercontent.com/36151/108834513-9052f280-75ce-11eb-9cf7-e7b0e2b45890.png)

**Affected version (please complete the following information):**
 - OpenShift: 6de597a7a3255f6f1a630fbdf7af21674f2609db
 - OpenDevStack ??

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```text
 > git lfs pull origin # timeout=10
Commit message: "Merge pull request #62 in ODM/odm-components from bugfix/ODM-509-trigger-mergedissueid to feature/ODM-508-debug-ods-regression"
[Pipeline] echo
context.projectId: >>odm
[Pipeline] echo
context.repoName: >>odm-components
[Pipeline] echo
context.gitCommitMessage: >>Merge-pull-request-62-in-ODM-odm-components-from-bugfix-ODM-509-trigger-mergedissueid-to-feature-ODM-508-debug-ods-regression
[Pipeline] echo
mergedIssueId: >>
[Pipeline] echo
mergedBranch: >>
```

**Additional context**

**Comment by segator** [comment] 2021-04-22 07:05
I think we need to have our own convention.
I recomend something like 
https://github.com/google-github-actions/release-please-action


fix: which represents bug fixes, and correlates to a SemVer patch.
feat: which represents a new feature, and correlates to a SemVer minor.
feat!:, or fix!:, refactor!:, etc., which represent a breaking change (indicated by the !) and will result in a SemVer major.

**Comment by clemensutschig** [comment] 2021-04-28 13:24
@michaelsauter can you maybe help solve this or @s2oBCN? @segator @metmajer

**Comment by michaelsauter** [comment] 2021-04-28 14:29
I could look into this early next week?

Convention etc. sounds like a separate topic :)

**Comment by michaelsauter** [comment] 2021-05-03 12:21
So I started writing a reproducing test for it and realised it's a bit complicated. Prior to the regression, we got the branch name (`bugfix/ODM-509-trigger-mergedissueid` in the example above) out of the Git message. After the regression, the branch name is not actually in the Git message, only a sanitised version of it (`bugfix-ODM-509-trigger-mergedissueid`). The problem is that from this sanitised message, the original branch name cannot be reconstructed as we do not know which hyphens were slashes. Of course we could guess but I would rather not.

I see two options:

a) reverting the sanitisation, and applying different logic
b) removing the "merged branch" functionality

@serverhorror @clemensutschig Thoughts?

**Comment by michaelsauter** [comment] 2021-05-04 06:04
OK, I have a new idea. We just keep the raw Git message in the context as well. Then this value can be used for the method - the regex will then continue to work and the branch name will be correct.

**Comment by michaelsauter** [comment] 2021-05-04 06:16
See #639. For users affected by this, I think the best workaround is to get the raw Git commit message yourself via `git log -1 --pretty=%B HEAD`.

I can also backport to 3.x once approved.

**Closed** 2021-05-06 06:31 UTC
Labels: bug

**Comment by borja44** [comment] 2021-05-19 08:23
@michaelsauter should we backport to 3.x?
