### ISSUE TITLE
[bug]: deploy to openshift fails when 'automatically ...' is unchecked in deployment config

### ISSUE THREAD

**Issue by SimonGolms** [opendevstack/ods-jenkins-shared-library#165] opened 2019-11-27 11:00 UTC
## Describe the bug

Our current DevOps process is that we still manually deploy our PROD in OpenShift by pressing the `deploy` button. Therefore the flag `Automatically start a new deployment when the deployment configuration changes` was deactivated in the deployment config. For the DEV environment the automatic deployment is wanted.

### Openshift

1. Go to `Edit Deployment Config frontend` (/console/project/hugo-test/edit/dc/frontend)
2. Scroll down to `Images` / `Container frontend`
3. Uncheck `Automatically start a new deployment when the image changes`
4. Uncheck `Automatically start a new deployment when the deployment configuration changes`

### Jenkins

1. Start Pipeline `hugo-cd/frontend-test`
2. Make sure stage `stageDeployToOpenshift()` is part of the pipeline
    ```groovy
    odsPipeline(
    ..
    ) { context ->
    ...
    stageDeployToOpenshift(context)
    }
    ```
3. Pipeline finish with error in stage `stageDeployToOpenshift()`

## **Expected behavior**

A successful `stageDeployToOpenshift()` stage regardless of the settings of your deployment config in OpenShift

## **Screenshots**

![image](https://user-images.githubusercontent.com/17799657/69717854-29196a80-110d-11ea-9709-852c925c5cf4.png)

## **Affected version**

- **OpenShift**: 3.11
- **OpenDevStack**: 1.2

## **Log Output**

**Console output from Jenkins Pipeline: `hugo-cd/frontend-test`**

```
[...]
Pushed 4/6 layers, 67% complete
Pushed 5/6 layers, 100% complete
Pushed 6/6 layers, 100% complete
Push successful
[Pipeline] }
[Pipeline] // timeout
[Pipeline] sh (find last build)
+ sleep 10
+ oc get build --sort-by=.status.startTimestamp -o 'jsonpath={.items[-1:].metadata.name},{.items[-1:].status.phase}' -n hugo-test -l buildconfig=frontend
[Pipeline] sh (find new image sha)
+ oc get istag frontend:14-2dd93fda -n hugo-test -o 'jsonpath={.image.dockerImageReference}'
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy to Openshift)
[Pipeline] openshiftTag
NOTE: steps like this one from the OpenShift Pipeline Plugin will not be supported against OpenShift API Servers later than v3.11


Starting "Tag OpenShift Image" with the source [image stream:tag] "frontend:14-2dd93fda" from the project "hugo-test" and destination stream(s) "frontend" with tag(s) "latest" from the project "hugo-test".


Exiting "Tag OpenShift Image" successfully.
[Pipeline] sh (find last image)
+ oc get istag frontend:latest -n hugo-test -o 'jsonpath={.image.dockerImageReference}'
[Pipeline] timeout
Timeout set to expire in 15 min
[Pipeline] {
[Pipeline] sh (find new deployment)
+ sleep 10
+ oc describe dc frontend -n hugo-test
+ grep -e docker-registry.default.svc:5000/hugo-test/frontend@sha256:c80646a09e971a7aeb17250a1bdaf6ad281816482e29766800ffe56f8b9bc756 -e Status -e 'Latest Version'
[Pipeline] echo
Found last deployment id: 33 - status Status:
[Pipeline] echo
OCP Deployment done - reporting status
[Pipeline] }
[Pipeline] // timeout
[Pipeline] error
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // wrap
[Pipeline] echo
***** Finished ODS Pipeline for  frontend (with error) *****
[...]
```

## Additional context

If you are rewriting this code section, so that you do not compare an array value from a grepped and splitted string to an hardcoded value the bug should be fixed quickly. It would be better to parse the response as json / yaml and read the value from it.

[`stageDeployToOpenshift.groovy`](https://github.com/opendevstack/ods-jenkins-shared-library/blob/1.2.x/vars/stageDeployToOpenshift.groovy)
```groovy
timeout(context.openshiftBuildTimeout) {
    while(true) {
    ocpDeployment = sh(returnStdout: true, script:"sleep 10 && oc describe dc ${context.componentId} -n ${context.targetProject} | grep -e ${ocpLatestImage} -e Status -e 'Latest Version'", label : "find new deployment").trim().split(/\s+/)

    echo ("Found last deployment id: ${ocpDeployment[2]} - status ${ocpDeployment[6]}")
    if (ocpDeployment[6] != "Pending" && ocpDeployment[6] != "Running") {
        echo "OCP Deployment done - reporting status"
        break
    }
    }
}
```

Compare the returns of `oc describe dc frontend -n hugo-test | grep -e docker-registry.default.svc:5000/hugo-test/frontend@sha256:ABC... -e Status -e 'Latest Version'` with checked and unchecked options and you should already see the difference and why the `.split()` creates this bug.

🎁 On the street they say something about a Bug Bounty Program, true?

**Comment by michaelsauter** [comment] 2019-11-27 11:23
@SimonGolms Thanks for reporting. Please note that `master` is not using the same commands, so will behave differently. It will trigger a manual rollout if you do not have triggers enabled. If you do not want that behaviour, you must write your own logic (which is easier on `master` as it provides building blocks to use)

**Comment by michaelsauter** [comment] 2019-11-27 11:28
Further, I think this is not a bug actually since that step does NOTHING except to "deploy". If you disable the triggers, no deployment happens .... if you do not want to deploy via the pipeline, remove the stage.

**Comment by SimonGolms** [comment] 2019-11-27 12:12
Unfortunately, I'm not a groovy expert, yet... but how can I skip the stage `stageDeployToOpenshift()` when I am on master, while on `dev` it should still execute it - Jenkinsfile for each branch; not using the lib and define my own `stageDeployToOpenshift()`? Can you please help me with a code example?

> Please note that `master` is not using the same commands, so will behave differently.

I'm confused, what are the different behaviors exactly and are there even more? Do you have a link to the section in the documentation?

**Comment by michaelsauter** [comment] 2019-11-27 14:50
You are running against `1.2.x`, which queries for deployment status. In your case this fails when no trigger is there.

`2.x` (which will include the functionality that is right now in `master`) will change this behaviour: it will check if there is a trigger, and if there is none, it will rollout manually.

I think what you want is something like this:
```
if (context.environment = 'dev') {
  stageDeployToOpenshift()
}
```

**Comment by SimonGolms** [comment] 2019-11-27 15:44
Ah, now I got it, by `master` branch you mean the one from this repo `ods-jenkins-shared-library`. I was assuming that this refers to `branchToEnvironmentMapping` and `master -> test / dev -> dev` from our project.

**Comment by michaelsauter** [comment] 2019-11-28 07:53
@SimonGolms Yes I was referring to `ods-jenkins-shared-library`.

**Comment by SimonGolms** [comment] 2019-12-05 15:32
Unfortunately to disable/skip the stage `stageDeployToOpenshift()` will not work as an current workaround. When stage `stageStartOpenshiftBuild()` is finished the label 'latest' in the image stream is no longer updated. A valid CI/CD process is currently not possible for us. 😞

**Comment by michaelsauter** [comment] 2019-12-05 15:42
@SimonGolms Just extract the image tagging of the deploy step into your Jenkinsfile. Of course a "valid" process is possible for you, but as you do not follow the standard deployment you are not able to use the standard stages. In the end, you can modify the stages to whatever you want them to be.

**Comment by SimonGolms** [comment] 2019-12-05 19:41
I am sorry, but as long as I don't know the definition of 'standard deployment', I cannot agree with you.

_IMHO: I cannot imagine that the last push of a button to release a productive system, which is here equivalent to pressing the deploy button, deviates from a certain standard..._

Anyway, I see light at the end of the tunnel with version 2.x and for all those who will also come into this situation, this is the code snippet that actually helps us as a workaround and has already been partially adopted from version 2.x, so thanks for that:

```groovy
odsPipeline(
...
) { context ->
  ...
  stageStartOpenshiftBuild(context)

  // workaround in ods-library@1.2.x until bugfix: https://github.com/opendevstack/ods-jenkins-shared-library/issues/165
  if (context.environment == 'test') {
    setLatestImageTag(context)
  } else {
    stageDeployToOpenshift(context)
  }
}

...

def setLatestImageTag(def context) {
  stage('Update Latest Tag') {
    sh(
      script: "oc -n ${context.targetProject} tag ${context.componentId}:${context.tagversion} ${context.componentId}:latest",
      label: "Update latest tag of is/${context.componentId} to ${context.tagversion}"
    )
  }
}
```

**Comment by renedupont** [comment] 2020-03-23 16:06
I suppose with 'standard' the way the stages (which are provided by the jenkins-shared-lib) work was meant, not a general process, but anyways, I hope this is resolved by now (maybe by moving to ODS 2)?
 
In case there is no other issue anymore regarding this, please close the ticket. Thanks!

**Comment by clemensutschig** [comment] 2020-03-31 08:26
@SimonGolms  any update?

**Comment by SimonGolms** [comment] 2020-03-31 08:34
We will update our project to version 2.x by the end of April and would close it then.

**Comment by clemensutschig** [comment] 2020-05-07 16:32
@michaelsauter tested? If so Please close.  ;-)

**Closed** 2020-05-07 16:51 UTC
