### ISSUE TITLE
BUILD_URL not set

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/ods-jenkins-shared-library#40] opened 2018-11-18 20:42 UTC
Last week, @tjaeschke and me were trying my setup. And we discoverd #69 and also a problem with BUILD_URL. This problem still exists. BUILD_URL is somehow not set (and I totally agree, it should be set by Jenkins):

 > git checkout -f 3181e0f9709b7a3470bc90da123a8ceecc46e8af
Commit message: "Initial commit"
[Pipeline] stage
[Pipeline] { (Prepare)
[Pipeline] error
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // wrap
[Pipeline] echo
Setting BitBucket build status to FAILED ...
[Pipeline] withCredentials
[Pipeline] // withCredentials
[Pipeline] echo
Could not set BitBucket build status to FAILED
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: BUILD_URL is required, but not set (usually provided by Jenkins)
Finished: FAILURE

Any ideas welcome. The pipeline uses the ods-library@master.
Is the BUILD_URL used later on in the shared library? Do we need it. And what is the behavior on your site?

**Comment by rattermeyer** [comment] 2018-11-19 15:40
I will check that. Basically it happens on the initial build already. So, when Jenkins is created and used for the initial code commit for a new project.

**Comment by rattermeyer** [comment] 2018-11-19 18:48
The fix described: Go to Manage Jenkins -> Configure System -> Save settings (without making any change).  works also for me.

**Comment by rattermeyer** [comment] 2018-11-19 18:50
jenkins.model.JenkinsLocationConfiguration is not even present on a freshly deployed Jenkins. that explains it.

**Comment by clemensutschig** [comment] 2018-11-19 18:53
@rattermeyer We could seed it in config.xml- that should be the right fix

**Comment by michaelsauter** [comment] 2018-11-20 07:48
Thanks for checking. I'm still confused why it does work for us ... at least most of the time :D

**Comment by clemensutschig** [comment] 2018-11-21 13:39
@michaelsauter  / @tjaeschke  @rattermeyer  - wasnt this fixed now?!

**Comment by michaelsauter** [comment] 2018-11-21 14:19
PR  #41 fixes the crash, but not the root cause. For that we need to set it during boot. We discussed that it might be possible to get the route from OpenShift via `oc`, but this needs a little bit of work.

**Comment by michaelsauter** [comment] 2018-11-22 07:59
I provisioned a new project, and now this also happens for us. I'll see if I can get the seeding to work.

**Comment by clemensutschig** [comment] 2018-11-22 08:43
@michaelsauter  - maybe it's because of master uptaking a new base image? (we are now on 3.11 :))

**Comment by michaelsauter** [comment] 2018-11-22 10:15
@clemensutschig Yes could be. Locally I can get the route via `oc get route jenkins -n foo-cd -o jsonpath='{.spec.host}'`, so I'll try to call this from the Jenkins instance on boot.

**Closed** 2018-11-29 14:35 UTC
Labels: bug
