### ISSUE TITLE
Error in building feature branch

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-jenkins-shared-library#27] opened 2018-10-24 15:03 UTC
I get an error in a new provisioned project after I have created a feature Branch via Jira. 

The master branch builds well in the test project, but the feature branch build fails with the following error and stacktrace in the dev Build on Jenkins.

The shared-lib version is 0.1-latest

`First time build. Skipping changelog.
[Pipeline] sh
[workspace] Running shell script
+ git rev-parse HEAD
[Pipeline] echo
Setting environment ...
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // wrap
[Pipeline] emailextrecipients
[Pipeline] emailext
An attempt to send an e-mail to empty list of recipients, ignored.
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method groovy.lang.GroovyObject setProperty java.lang.String java.lang.Object (org.ods.OdsContext.env)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.StaticWhitelist.rejectMethod(StaticWhitelist.java:180)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor$2.reject(SandboxInterceptor.java:192)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onSetProperty(SandboxInterceptor.java:235)
	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:340)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedSetProperty(Checker.java:347)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.setProperty(SandboxInvoker.java:33)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawSet(PropertyAccessBlock.java:24)
	at org.ods.OdsContext.determineEnvironment(file:/var/lib/jenkins/jobs/kalo-cd/jobs/kalo-cd-be-spring-boot-dev/builds/3/libs/ods-library/src/org/ods/OdsContext.groovy:413)
	at org.ods.OdsContext.assemble(file:/var/lib/jenkins/jobs/kalo-cd/jobs/kalo-cd-be-spring-boot-dev/builds/3/libs/ods-library/src/org/ods/OdsContext.groovy:138)
	at org.ods.OdsPipeline.execute(file:/var/lib/jenkins/jobs/kalo-cd/jobs/kalo-cd-be-spring-boot-dev/builds/3/libs/ods-library/src/org/ods/OdsPipeline.groovy:28)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.set(PropertyishBlock.java:88)
	at com.cloudbees.groovy.cps.impl.AssignmentBlock$ContinuationImpl.assignAndDone(AssignmentBlock.java:70)
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:60)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:109)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:82)
	at sun.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:122)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:261)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:35)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:108)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:32)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:174)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:331)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$100(CpsThreadGroup.java:82)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:243)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:231)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

**Comment by clemensutschig** [comment] 2018-10-24 15:51
`  *[<413>     script:"oc project ${name} &> /dev/null",](url)**`

**Comment by clemensutschig** [comment] 2018-10-24 16:02
@tjaeschke  - check out

https://stackoverflow.com/questions/38276341/jenkins-ci-pipeline-scripts-not-permitted-to-use-method-groovy-lang-groovyobject

we have to fix something here :)

**Comment by michaelsauter** [comment] 2018-10-25 09:18
The issue is `Scripts not permitted to use method groovy.lang.GroovyObject setProperty java.lang.String java.lang.Object (org.ods.OdsContext.env)` - somewhere the shared lib tries to call `context.env`, but apparently there is no `org.ods.OdsContext.getEnv` defined. I didn't have a look at the code yet, but we should probably fix it :) It might be fixed in the latest master ...

**Comment by michaelsauter** [comment] 2018-10-26 13:59
I've updated the tag, so this should be fixed now.

**Closed by michaelsauter** 2018-10-26 13:59 UTC
Labels: bug
